### ISSUE TITLE
EXCLUDE_GLOBS for aws-sdk

### ISSUE THREAD

**Issue by GitTom** [motdotla/node-lambda#130]
I can't get the EXCLUDE_GLOBS syntax right for excluding the AWS SDK.

The SDK is quite big and comes with Lambda's node - currently v2.4.2 and it appears they keep it fairly up-to-date - so I think it is important to exclude it.  Actually, I would suggest adding it to the example .env [here](https://github.com/motdotla/node-lambda/blob/2c3b9021f90b0e3ec625300d52dda6eb8a7cdb3a/lib/.env.example#L15).

`EXCLUDE_GLOBS=*.md  event*.json .env .eslint* samples speechAssets* aws-sdk`

I tried a bunch of things but none worked.

**Comment by DeviaVir** [comment]
@GitTom Please try to encapsulate in `"`'s and give it another try

**Comment by GitTom** [comment]
Ok, tried that, but node_modules/aws-sdk still gets added to the deployment zip.

EXCLUDE_GLOBS is working for everything else for me, but the aws-sdk is the only directory 2 levels down that I'm trying to exclude.

**Comment by DeviaVir** [comment]
So, `EXCLUDE_GLOBS` actually does its job here, we install `package.json` ourselves again which is what places the `aws-sdk` into your ZIP.
Others have had success using `--prebuiltDirectory` (https://github.com/motdotla/node-lambda/pull/122)

**Comment by DeviaVir** [comment]
Yep, keep an eye on https://github.com/motdotla/node-lambda/issues/128 for that release

**Comment by MkFoster** [comment]
In case you land here because you are trying to shave off the 30+MBytes the aws-sdk adds to your deployment package, I found that simply moving the aws-sdk to the devDependencies section of the package.json does the trick.  

The aws-sdk will be installed under node_modules when you run "npm install" so you can test locally but when when you do "node-lambda deploy" it will be excluded because by default node-lambda adds the "--production" parameter when it does the npm install for building the deployment package (which it clearly says in the output when I run node-lambda if I had bothered to read it).  The npm install "--production" parameter indicates that you want to exclude dev dependencies from your install.  See the npm docs here for details: https://docs.npmjs.com/cli/install

Here is the relevant section in an example package.json:
  "dependencies": {
    "cookie": "^0.3.1"
  },
  "devDependencies": {
    "aws-sdk": "^2.263.1"
  }

**Comment by SergeyAvd** [comment]
> 
> 
> In case you land here because you are trying to shave off the 30+MBytes the aws-sdk adds to your deployment package, I found that simply moving the aws-sdk to the devDependencies section of the package.json does the trick.
> 

Thanks for a hint! But for my case, it does still include the entirety of AWS-SDK. That's because I'm using dynamodb npm module and that should be the prod dependency. Thus npm sees that production dependency (dynamodb) uses AWS-SDK and includes that as well.
