### ISSUE TITLE
Deploy function does not include modules from npm link

### ISSUE THREAD

**Issue by green-mdoerflinger** [motdotla/node-lambda#97]
When in link modules into my project  using `npm link` (symbolic link - used for unpublished local modules), these modules are not included the package uploaded to AWS using `node-lambda deploy`. 
Is it possible to extend node-lambda to include linked modules?

**Comment by DeviaVir** [comment]
@green-mdoerflinger This is because we are running an `npm install` ourselves, around this parts:
https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L165

You can run your links in the PostInstall, for documentation please refer to https://github.com/motdotla/node-lambda#post-install-script
